### DISCUSSION TITLE
Error 502 on all management API requests

### DISCUSSION THREAD

**Discussion by flifloo** [netbirdio/netbird#573] [Q&A / Support] [answered]
Hi, I'm working on self-hosting NetBird, and after a lot of fight with the configuration I got a part of the stack working.

But now, when I go to the dashboard, the manager API returns a lot of 502 errors :

![image](https://user-images.githubusercontent.com/12417808/203160691-8253add4-5ae0-4bb6-a83d-47de25036c17.png)

![image](https://user-images.githubusercontent.com/12417808/203160649-9f84d0fc-a756-4a52-81be-49b6cfbcfcd5.png)

#### The logs of the management docker :

<details>

```
2022/11/21 20:37:14 http: panic serving 172.18.0.23:58628: runtime error: index out of range [0] with length 0
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:1825 +0xbf
github.com/netbirdio/netbird/management/server/http/middleware.getPemCert(...)
        /home/runner/work/netbird/netbird/management/server/http/middleware/handler.go:81
github.com/netbirdio/netbird/management/server/http/middleware.NewJwtMiddleware.func1(0xc00011a190)
        /home/runner/work/netbird/netbird/management/server/http/middleware/handler.go:46 +0x38c
github.com/netbirdio/netbird/management/server/http/middleware.(*JWTMiddleware).ValidateAndParse(0xc000352190, {0xc00013a008?, 0x7fc302697a00?})
        /home/runner/work/netbird/netbird/management/server/http/middleware/jwt.go:225 +0xda
github.com/netbirdio/netbird/management/server/http/middleware.(*JWTMiddleware).CheckJWTFromRequest(0xc000352190, {0xd87618, 0xc000096100}, 0xc00027c300)
        /home/runner/work/netbird/netbird/management/server/http/middleware/jwt.go:189 +0x26f
github.com/netbirdio/netbird/management/server/http/middleware.(*JWTMiddleware).Handler.func1({0xd87618, 0xc000096100}, 0xc0001f6348?)
        /home/runner/work/netbird/netbird/management/server/http/middleware/jwt.go:113 +0x4a
net/http.HandlerFunc.ServeHTTP(0xc00036c000?, {0xd87618?, 0xc000096100?}, 0xc00027c300?)
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2084 +0x2f
net/http.HandlerFunc.ServeHTTP(0xb74360?, {0xd87618?, 0xc000096100?}, 0x2e?)
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2084 +0x2f
        /home/runner/work/netbird/netbird/management/server/telemetry/http_api_metrics.go:147 +0x254
net/http.HandlerFunc.ServeHTTP(0xc00027c100?, {0xd884b8?, 0xc000160000?}, 0x800?)
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2084 +0x2f
net/http.HandlerFunc.ServeHTTP(0x40?, {0xd884b8?, 0xc000160000?}, 0xc000680000?)
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2084 +0x2f
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0xd83e00?, 0xc00007e0a0?}, 0xc00047e000?}, {0xd884b8, 0xc000160000}, 0xc0000b0400)
        /home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20220630215102-69896b714898/http2/h2c/h2c.go:113 +0x49f
net/http.serverHandler.ServeHTTP({0xc0002648a0?}, {0xd884b8, 0xc000160000}, 0xc0000b0400)
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001a7400, {0xd891d8, 0xc000306180})
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:3071 +0x4db
```
</details>

#### My `docker-compose.yml` config :

<details>

```yaml
version: "3"

services:
  #UI dashboard
  dashboard:
    image: wiretrustee/dashboard:main
    container_name: "netbird_dashboard"
    restart: unless-stopped
    environment:
      - AUTH_AUDIENCE=netbird
      - AUTH_CLIENT_ID=netbird
      - AUTH_AUTHORITY=https://auth.****REDACTED****
      - AUTH_DEVICE_AUTH_ENDPOINT=https://auth.****REDACTED****
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - NETBIRD_MGMT_API_ENDPOINT=https://vpn.****REDACTED****:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://vpn.****REDACTED****:443
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbird.rule=Host(`vpn.****REDACTED****`)"
      - "traefik.http.routers.netbird.entrypoints=websecure"

  # Signal
  signal:
    image: netbirdio/signal:latest
    container_name: "netbird_signal"
    restart: unless-stopped
    volumes:
      - /home/docker/netbird/signal:/var/lib/netbird
    environment:
      - SSL_CERT_FILE=
    networks:
      - traefik
    expose:
      - 10000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbird-signal.rule=(Host(`vpn.****REDACTED****`) && PathPrefix(`/signalexchange`))"
      - "traefik.http.routers.netbird-signal.entrypoints=websecure"
      - "traefik.http.routers.netbird-signal.service=netbird-signal"
      - "traefik.http.services.netbird-signal.loadbalancer.server.scheme=h2c"

  management:
    image: netbirdio/management:latest
    container_name: "netbird_management"
    restart: unless-stopped
    depends_on:
      - dashboard
    volumes:
      - /home/docker/netbird/mgmt:/var/lib/netbird
      - /home/docker/netbird/management.json:/etc/netbird/management.json
    command:
      - "--port=80"
      - "--log-file=console"
      - "--disable-anonymous-metrics=false"
      - "--disable-single-account-mode"
      - "--dns-domain=netbird.selfhosted"
    expose:
      - 80
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbird-api.rule=(Host(`vpn.****REDACTED****`) && PathPrefix(`/api`))"
      - "traefik.http.routers.netbird-api.entrypoints=websecure"
      - "traefik.http.routers.netbird-api.service=netbird-api"
      - "traefik.http.services.netbird-api.loadbalancer.server.scheme=http"
      - "traefik.http.routers.netbird-management.rule=(Host(`vpn.****REDACTED****`) && PathPrefix(`/management`))"
      - "traefik.http.routers.netbird-management.entrypoints=websecure"
      - "traefik.http.routers.netbird-management.service=netbird-management"
      - "traefik.http.services.netbird-management.loadbalancer.server.scheme=h2c"


  # Coturn
  coturn:
    image: coturn/coturn
    container_name: "netbird_coturn"
    restart: unless-stopped
    domainname: vpn.****REDACTED****
    volumes:
      - /home/docker/netbird/turnserver.conf:/etc/turnserver.conf:ro
    network_mode: host

networks:
  traefik:
    external: true
```
</details>

#### My `management.json` config :

<details>

```json
{
  "Stuns": [
    {
      "Proto": "udp",
      "URI": "stun:vpn.****REDACTED****:3478",
      "Username": "",
      "Password": null
    }
  ],
  "TURNConfig": {
    "Turns": [
      {
        "Proto": "udp",
        "URI": "turn:vpn.****REDACTED****:3478",
        "Username": "self",
        "Password": "****REDACTED****"
      }
    ],
    "CredentialsTTL": "12h",
    "Secret": "secret",
    "TimeBasedCredentials": false
  },
  "Signal": {
    "Proto": "http",
    "URI": "vpn.****REDACTED****:443",
    "Username": "",
    "Password": null
  },
  "Datadir": "",
  "HttpConfig": {
    "Address": "0.0.0.0:80",
    "AuthIssuer": "https://auth.****REDACTED****",
    "AuthKeysLocation": "https://auth.****REDACTED****/oauth2/jwks",
    "AuthAudience": "netbird",
    "OIDCConfigEndpoint": "https://auth.****REDACTED****/.well-known/openid-configuration"
  },
  "IdpManagerConfig": {
    "Manager": "none"
  },
  "DeviceAuthorizationFlow": {
    "Provider": "hosted",
    "ProviderConfig": {
      "Audience": "netbird",
      "Domain": "auth.****REDACTED****",
      "ClientID": "netbird",
      "TokenEndpoint": "https://auth.****REDACTED****/oauth2/token",
      "DeviceAuthEndpoint": ""
    }
  }
}
```
</details>

I can't figure out what's happening, can someone please help me ?
