### ISSUE TITLE
Unable to login any client without a setup-key (android, macos)

### ISSUE THREAD

**Issue by subhamagr** [netbirdio/netbird#1662]
**Describe the problem**

A clear and concise description of what the problem is.

Notes:
Netbird domain: `netbird.example.com`
Zitadel domain: `auth.example.com`

I am able to log into the netbird admin, but I cannot register any peer who is not using a setup-key - macos, android. Everytime I try to register a peer, the see the following errors - [netbird-android](https://github.com/netbirdio/netbird/assets/7915409/f7ec5b33-9a93-429a-b0e0-fbca96ebf048). Similar error on macos login via browser.

Also, I am trying to login using the admin account.

on the server, I only see the following logs (docker):

```
netbird-management  | 2024-03-04T04:58:59Z DEBG management/server/grpcserver.go:324: Login request from peer [7+gqegJg0AQxbWeAx56n8nQ3MA1ZrCbW180+9vAzBSw=] [xx.xx.xx.xx] (IP of the client)

netbird-management  | 2024-03-04T04:58:59Z WARN management/server/grpcserver.go:363: failed logging in peer 7+gqegJg0AQxbWeAx56n8nQ3MA1ZrCbW180+9vAzBSw=
```

**To Reproduce**

1. Click on `Connect` on android/macos UI.
2. You get redirected to zitadel for auth, enter username, password and 2fa code.
3. you get redirected back to netbird `/auth?code=`

**Expected behavior**

Peer is registered successfully.

**Are you using NetBird Cloud?**

I am using self-hosted NetBird with selfhosted Zitadel.

**NetBird version**: 

`netbird version`- 0.26.2

**Screenshots**

[netbird-android](https://github.com/netbirdio/netbird/assets/7915409/f7ec5b33-9a93-429a-b0e0-fbca96ebf048)

**Configs**

1. Docker compose
```
---
version: "3"

services:
  # UI dashboard
  netbird-dashboard:
    image: netbirdio/dashboard:v2.1.2
    container_name: netbird-dashboard
    restart: unless-stopped
    env_file:
      - ./dashboard.env
    networks:
      - caddy_proxy

  # Signal
  netbird-signal:
    image: netbirdio/signal:0.26.2
    container_name: netbird-signal
    restart: unless-stopped
    user: "1002:1002"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /deploy/data/netbird/signal:/var/lib/netbird
#     command: ["--letsencrypt-domain", "$NETBIRD_LETSENCRYPT_DOMAIN", "--log-file", "console"]
    networks:
      - caddy_proxy

  # Management
  netbird-management:
    image: netbirdio/management:0.26.2
    container_name: netbird-management
    restart: unless-stopped
    user: "1002:1002"
    depends_on:
      - netbird-dashboard
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /deploy/data/netbird/management:/var/lib/netbird
      - ./management.json:/etc/netbird/management.json
    command: [
      "--port", "80",
      "--log-file", "console",
      "--log-level", "debug",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.example.com",
      "--dns-domain=net.netbird.example.com",
    ]
    networks:
      - caddy_proxy

  # Coturn
  netbird-coturn:
    image: coturn/coturn:4.6.2-alpine
    container_name: netbird-coturn
    restart: unless-stopped
    user: "1002:1002"
    domainname: netbird.example.com
    network_mode: host
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./turnserver.conf:/etc/turnserver.conf:ro
    #      - ./privkey.pem:/etc/coturn/private/privkey.pem:ro
    #      - ./cert.pem:/etc/coturn/certs/cert.pem:ro
    command:
      - -c /etc/turnserver.conf

networks:
  caddy_proxy:
    external: true
    
```

2. turnserver.conf (`grep "^[^#;]" turnserver.conf`)
```
listening-port=3478
tls-listening-port=5349
external-ip=<Public-IP>
min-port=49152
max-port=65535
fingerprint
lt-cred-mech
user=self:<password>
realm=wiretrustee.com
cert=/etc/coturn/certs/cert.pem
pkey=/etc/coturn/private/privkey.pem
log-file=stdout
no-software-attribute
pidfile="/var/tmp/turnserver.pid"
no-cli

```

3. management.json

```
{
    "Stuns": [
        {
            "Proto": "udp",
            "URI": "stun:example.com:3478",
            "Username": "",
            "Password": null
        }
    ],
    "TURNConfig": {
        "Turns": [
            {
                "Proto": "udp",
                "URI": "turn:netbird.example.com:3478",
                "Username": "self",
                "Password": "password"
            }
        ],
        "CredentialsTTL": "12h",
        "Secret": "secret",
        "TimeBasedCredentials": false
    },
    "Signal": {
        "Proto": "https",
        "URI": "netbird.example.com:443",
        "Username": "",
        "Password": null
    },
    "ReverseProxy": {
        "TrustedHTTPProxies": [],
        "TrustedHTTPProxiesCount": 0,
        "TrustedPeers": [
             "0.0.0.0/0"
        ]
    },
    "Datadir": "/var/lib/netbird/",
    "DataStoreEncryptionKey": "db-key",
    "StoreConfig": {
        "Engine": "sqlite"
    },
    "HttpConfig": {
        "Address": "0.0.0.0:443",
        "AuthIssuer": "https://auth.example.com",
        "AuthAudience": "client@netbird",
        "AuthKeysLocation": "https://auth.example.com/oauth/v2/keys",
        "AuthUserIDClaim": "",
        "CertFile": "",
        "CertKey": "",
        "IdpSignKeyRefreshEnabled": true,
        "OIDCConfigEndpoint": "https://auth.example.com/.well-known/openid-configuration"
    },
    "IdpManagerConfig": {
        "ManagerType": "zitadel",
        "ClientConfig": {
            "Issuer": "https://auth.example.com",
            "TokenEndpoint": "https://auth.example.com/oauth/v2/token",
            "ClientID": "netbird",
            "ClientSecret": "secret-key",
            "GrantType": "client_credentials"
        },
        "ExtraConfig": {
            "ManagementEndpoint": "https://auth.example.com/management/v1"
        },
        "Auth0ClientCredentials": null,
        "AzureClientCredentials": null,
        "KeycloakClientCredentials": null,
        "ZitadelClientCredentials": null
     },
    "DeviceAuthorizationFlow": {
        "Provider": "hosted",
        "ProviderConfig": {
          "Audience": "client@netbird",
          "AuthorizationEndpoint": "",
          "Domain": "",
          "ClientID": "client@netbird",
          "ClientSecret": "",
          "TokenEndpoint": "https://auth.example.com/oauth/v2/token",
          "DeviceAuthEndpoint": "https://auth.example.com/oauth/v2/device_authorization",
          "Scope": "openid",
          "UseIDToken": false,
          "RedirectURLs": null
         }
    },
    "PKCEAuthorizationFlow": {
        "ProviderConfig": {
            "Audience": "client@netbird",
            "ClientID": "client@netbird",
            "ClientSecret": "",
            "Domain": "",
            "AuthorizationEndpoint": "https://auth.example.com/oauth/v2/authorize",
            "TokenEndpoint": "https://auth.example.com/oauth/v2/token",
            "Scope": "openid profile email offline_access api",
            "RedirectURLs": [
                "https://netbird.example.com/auth",
                "https://netbird.example.com/silent-auth"
            ],
            "UseIDToken": false
        }
    }
}

```

4. dashboard.env
```
# Endpoints
NETBIRD_MGMT_API_ENDPOINT=https://netbird.example.com:443
NETBIRD_MGMT_GRPC_API_ENDPOINT=https://netbird.example.com:443

# OIDC
AUTH_AUDIENCE=client@netbird
AUTH_CLIENT_ID=client@netbird
AUTH_CLIENT_SECRET=
AUTH_AUTHORITY=https://auth.example.com
USE_AUTH0=false
AUTH_SUPPORTED_SCOPES="openid profile email offline_access api"
AUTH_REDIRECT_URI=/auth
AUTH_SILENT_REDIRECT_URI=/silent-auth
NETBIRD_TOKEN_SOURCE=accessToken

# SSL
NGINX_SSL_PORT=443

# Letsencrypt
LETSENCRYPT_DOMAIN=
LETSENCRYPT_EMAIL=

```
