### ISSUE TITLE
Broken hostnames when run through docker

### ISSUE THREAD

**Issue by Blake-Ballew** [netbirdio/netbird#1720]
I find that when I connect a peer to my network through netbird in a docker container, I cannot connect to other peers with their hostnames; only their IP addresses. All peers with netbird installed directly to the system work as expected. I am self hosting the netbird server.

1. docker-compose up -d the following docker-compose.yaml:

```
version: '3.4'
services:
  netbird:
    image: netbirdio/netbird:latest
    restart: always
    environment:
      - NB_MANAGEMENT_URL=<Management URL>
      - NB_SETUP_KEY=<Setup Key>
    volumes:
      - netbird-client:/etc/netbird
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    privileged: true
volumes:
  netbird-client:
    external: true
```

2. Ping the IP of a peer to ensure the network is running.
3. Ping the hostname of a peer with and without netbird.selfhosted.

Expected behavior is being able to successfully ping another peer with the hostname when running netbird in a docker container.

I am using netbird selfhosted.

Netbird version v0.26.3
