### ISSUE TITLE
Docker routing peers

### ISSUE THREAD

**Issue by chris-si** [netbirdio/netbird#2264]
I have a netbird client (container) deployed in a docker network to access the services from this specific docker network. To access these services, I manually assigned a network to the docker network, static ip addresses to every container and set a network route. With this setup I can reach every container via its ip address.

I have a second (managed) docker network in which I cannot manually assign a network and ip addresses for different reasons. But every container can reach every other container via the defined name of the service (via default docker network communication).
If I'm not mistaken, at the moment there is no viable way to access other containers in the same docker network where the netbird container is running in.

The netbird ssh server is not a viable option to e.g. proxy requests, since the application which tries to access the containers can't use ssh clients.

For this case it would be great if e.g. there would be a new network route type option. This new option would allow setting new routes via e.g. a custom name or directly the container name, so the netbird docker container would route to the appropriate container in the docker network.

---

Example:

There are three containers (including the netbird client) with the following names in a docker network on a remote server:
- `containerA`
- `containerB`
- `netbird-client` (which is also the netbird client peer name)

Now I'd like to be able to define a new route via the dashboard that either
- just says `containerA` is reachable via the routing peer client `netbird-client`
  - if I e.g. do `ping containerA` from another device connected to the netbird network, `netbird-client` should route the requests via the docker network to `containerA`
  - since e.g. the current `domain` routing peer type option requires a TLD it can't be used to reflect just container/service names
- or define some kind of CNAME record or additonal device names (like the netbird client names) that allows to map a custom name or domain to a container/service name and route the requests accordingly
  - e.g.
    - `myContainer` &rarr; `containerA`
    - `my-custom.domain.tld` &rarr; `containerA`

**Comment by nazarewk** [comment]
@chris-si this might be covered by the new Networks feature when specifying domains for the specific Resources?

**Comment by soleuniverse101** [comment]
> [@chris-si](https://github.com/chris-si) this might be covered by the new Networks feature when specifying domains for the specific Resources?

I'm running into a similar issue and I currently can't route traffic for a specific domain to the client inside Docker because domain names must be valid (e.g. example.com), they can't be only the target container's name

**Comment by davide-acanfora** [comment]
Here's how I currently solved this for my setup, where I need to expose a Postgres container via the NetBird client container.

First, I added both containers to the same network called `postgres`. Then I added an **alias** for the Postgres container for that network, so that the NetBird container can always contact it via the hostname `database.internal.mydomain.com`, regardless of its IP address. Here is my (simplified) `docker-compose.yml`:
```yaml
services:
  database:
    container_name: database
    image: postgres:18.0-alpine3.21
    networks:
      postgres:
        aliases:
          - database.internal.mydomain.com <-- additional hostname in the 'postgres' network

  netbird-client:
    container_name: netbird-client
    image: netbirdio/netbird:latest
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    environment:
      - NB_MANAGEMENT_URL=https://netbird.mydomain.com
      - NB_SETUP_KEY=...
    volumes:
      - ./netbird-data:/var/lib/netbird
    networks:
      - postgres

networks:
  postgres:
    external: true
```
Finally, I used the **Networks** feature, where I declared a network called `Internal` containing a resource called `Database` at the address `database.internal.mydomain.com`, accessible through the NetBird client container:

<img width="1246" height="873" alt="Image" src="https://github.com/user-attachments/assets/09694def-2d12-4b0a-b52a-619f05abb327" />

Note that if the **DNS domain** of your NetBird network is, for example, `netbird.mydomain.com`, you may encounter issues if you declare your resources as `database.netbird.mydomain.com` (instead of `database.something.else`), as peers will be unable to resolve that domain. I assume this occurs because peers believe that the resource is another peer as well, since it shares the same DNS domain in its hostname.

That's why I came up with the prefix `internal` to add to my domain to access the resources. To be honest, the alias in docker-compose could have been anything, even just `database.internal`. But if I had used it for a web service and entered it as a URL in the browser, something like `my-web-app.internal` would not be immediately recognized as such without adding the HTTP protocol in front of it. However, with the FQDN `my-web-app.internal.mydomain.com`, it would be
