### ISSUE TITLE
OIDC: wrong host for .well-known/openid-configuration

### ISSUE THREAD

**Issue by Cheezzhead** [netbirdio/netbird#2442]
**Describe the problem**

I get an `Error: Unauthenticated` message upon opening the dashboard homepage. Checking the browser's development console, it is attempting to fetch the OIDC configuration from `http://localhost/.well-known/openid-configuration` which is obviously wrong. I can't find the (environment?) variable to change this.

Additionally (not sure if related), but the [setup script](https://github.com/netbirdio/netbird/blob/main/infrastructure_files/configure.sh) generates an `openid-configuration.json` file which is never used in the generated compose file. Is this intentional?

**To Reproduce**

Relevant part from `docker-compose.yml`:
```
services:
  dashboard:
    image: netbirdio/dashboard:latest
    # ...
    environment:
      # ...
      # OIDC
      - AUTH_AUDIENCE=netbird
      - AUTH_CLIENT_ID=clientId
      - AUTH_CLIENT_SECRET=clientSecret
      - AUTH_AUTHORITY=https://auth.domain.tld
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api groups
      - NETBIRD_TOKEN_SOURCE=accessToken
      # ...

  management:
    image: netbirdio/management:latest
    // ...
    ports:
      - 33073:443
    command: [
      "--port", "443",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=net.doman.tld",
      "--dns-domain=netbird.selfhosted",
      # Only if dashboard doesn't exist/enable letsencrypt
      "--letsencrypt-domain", "net.domain.tld", 
    ]
    volumes:
      - netbird-mgmt:/var/lib/netbird
      - letsencrypt:/etc/letsencrypt:ro
      - ./management.json:/etc/netbird/management.json
```

`management.json`:
```
{
    "Stuns": [
      {
        "Proto": "udp",
        "URI": "stun:net.domain.tld:3478",
        "Username": "",
        "Password": null
      }
    ],
    "TURNConfig": {
      "Turns": [
        {
          "Proto": "udp",
          "URI": "turn:net.domain.tld:3478",
          "Username": "self",
          "Password": "ZTgDOSevQghQDn6ZMgVYKld4vB0hXQ5dZ23cYM5pG0M"
        }
      ],
      "CredentialsTTL": "12h",
      "Secret": "secret",
      "TimeBasedCredentials": false
    },
    "Signal": {
      "Proto": "https",
      "URI": "net.domain.tld:10000",
      "Username": "",
      "Password": null
    },
    "ReverseProxy": {
      "TrustedHTTPProxies": [],
      "TrustedHTTPProxiesCount": 0,
      "TrustedPeers": [
        "0.0.0.0/0"
      ]
    },
    "Datadir": "",
    "DataStoreEncryptionKey": "",
    "StoreConfig": {
      "Engine": "sqlite"
    },
    "HttpConfig": {
      "Address": "0.0.0.0:33073",
      "AuthIssuer": "https://auth.domain.tld",
      "AuthAudience": "netbird",
      "AuthKeysLocation": "https://auth.domain.tld/jwks.json",
      "AuthUserIDClaim": "preferred_username",
      "CertFile": "",
      "CertKey": "",
      "IdpSignKeyRefreshEnabled": false,
      "OIDCConfigEndpoint": "https://auth.domain.tld/.well-known/openid-configuration"
    },
    "IdpManagerConfig": {
      "ManagerType": "",
      "ClientConfig": {
        "Issuer": "https://auth.domain.tld",
        "TokenEndpoint": "https://auth.domain.tld/api/oidc/token",
        "ClientID": "",
        "ClientSecret": "",
        "GrantType": "client_credentials"
      },
      "ExtraConfig": {},
      "Auth0ClientCredentials": null,
      "AzureClientCredentials": null,
      "KeycloakClientCredentials": null,
      "ZitadelClientCredentials": null
    },
    "DeviceAuthorizationFlow": {
      "Provider": "none",
      "ProviderConfig": {
        "Audience": "netbird",
        "AuthorizationEndpoint": "",
        "Domain": "",
        "ClientID": "",
        "ClientSecret": "",
        "TokenEndpoint": "https://auth.domain.tld/api/oidc/token",
        "DeviceAuthEndpoint": "null",
        "Scope": "openid",
        "UseIDToken": false,
        "RedirectURLs": null
      }
    },
    "PKCEAuthorizationFlow": {
      "ProviderConfig": {
        "Audience": "netbird",
        "ClientID": "mMZH_ychgEKCMF73v0gFvy1~aSL7uCzS6oBJu8qVJrik4Kr.g_zQtonWEioCXRl746yFO.eC",
        "ClientSecret": "G1wY.vEQTCrMaHuPhnhCzR~Vc~LONL_Y.3UNBRRR5sy-vpgd36xSjRPetNrApOEe3i~p5bNg",
        "Domain": "",
        "AuthorizationEndpoint": "https://auth.domain.tld/api/oidc/authorization",
        "TokenEndpoint": "https://auth.domain.tld/api/oidc/token",
        "Scope": "openid profile email offline_access api groups",
        "RedirectURLs": [
          "http://localhost:53000"
        ],
        "UseIDToken": false
      }
    }
  }
  ```

**Expected behavior**

The configuration should be retrieved from `https://auth.domain.tld/.well-known/oidc-configuration`.

**Are you using NetBird Cloud?**

Self-hosted

**NetBird version**

0.28.7

**Comment by collse** [comment]
it should be in your management.json https://<your.domain.tld>/application/o/netbird/.well-known/openid-configuration",

**Comment by manju-rn** [comment]
Actually I have the similar issue.  I am using Zitadel - I was wondering what is the use of below which is setup in the management.json   . I am using zitadel and I am not using this redirect URL.  Even if I setup this up, where would this point to since myzitadel server is seperate from say netbird server?
```
        "RedirectURLs": [
          "http://localhost:53000"
```

**Comment by Cheezzhead** [comment]
> it should be in your management.json https://<your.domain.tld>/application/o/netbird/.well-known/openid-configuration",
> 
> the mangement.json itself is mounted as a volume in the docker-compose.yml in the management service

Yes, I modified my original post to include the netbird management service config. the `management.json` is indeed mounted as a volume, but I'm still getting the wrong redirect localhost.

I can't really see which property in the `management.json` would/could be responsible for this, but maybe you can point me in the right direction.

**Comment by sabya-oneassure** [comment]
Facing the same issue

**Comment by wiiun** [comment]
Facing the same issue

**Comment by ennbou** [comment]
after finishing all required setups and run ```docker compose log management```
I got

**Comment by ennbou** [comment]
I tried `curl` to get the json response directly from my local terminal works perfectly, but in my VPS didn't work, the issue was related to `Cloudflare` security, the http request works on the browser but doesn't work with curl.
 I fixed the problem by whitelisting my VPS's IPv4/IPv6 in Cloudflare WAF.

**Comment by finch-alt** [comment]
The problem still exists, docker with zitadel setup cannot be used.

**Comment by sergeycherepanov** [comment]
The problem still exists, docker with zitadel setup cannot be used.

**Comment by ekozan** [comment]
Sorry to bump, stuck on same thing any new ?

**Comment by brandtjo** [comment]
I did try to set up the self hosted compose stack with auth0 and actually forgot to perform step 5 which sets up the machine to machine application https://docs.netbird.io/selfhosted/identity-providers#step-5-create-and-configuire-machine-to-machine-application

Especially watch out for the quoted list of changed lines in setup.env at the end of that list, there are some changes that weren't mentioned in the guide before. 

Once I completely restarted everything (with removing the created volumes `docker-compose down --volumes`, and re-running `./configure`) everything came up.

Hope this helps.

**Comment by nazarewk** [comment]
Hello @Cheezzhead,

We're currently reviewing our open issues and would like to verify if this problem still exists in the [latest NetBird version](https://github.com/netbirdio/netbird/releases).

Could you please confirm if the issue is still there?

We may close this issue temporarily if we don't hear back from you within **2 weeks**, but feel free to reopen it with updated information.

Thanks for your contribution to improving the project!

**Comment by Johgaaa** [comment]
Im encountering the same issue. Running netbird v0.44.0 using authentik.
Netbird tries to fetch `http://localhost/.well-known/openid-configuration` when accessing the webpage.

**Comment by LennartStoehr** [comment]
Also experiencing this issue, tried authentik and zitadel, using netbird v0.46.0.
According to the logs, the management service gets its configuration from the correct endpoint (`https://auth.domain.com/.well-known/openid-configuration`) and is also able to log in to the service account to fetch users. The dashboard however always tries to get its openid configuration from `http://localhost/.well-known/openid-configuration`. 
Please reopen this issue.

**Comment by trevorsargent** [comment]
i'm also facing this issue using auth0 - v0.40.0

**Comment by arminfro** [comment]
I'm also facing the same issue with netbird v0.49.0 and keycloak v26.2.5.

I've hacked around it by configuring nginx to proxy-pass the request to the desired location, something like:
```nginx
http {
  server {
    server_name auth.mydomain.org;
    # ...
    location /.well-known/openid-configuration {
      # ...
      proxy_pass https://auth.mydomain.org/realms/netbird/.well-known/openid-configuration;
    }
  }
}
```

**Comment by nazarewk** [comment]
@arminfro sounds like something `$NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT` should handle this:

https://github.com/netbirdio/netbird/blob/86c4b7e6f47df1bf754dda735b97ce80c58422dc/infrastructure_files/configure.sh#L132-L152

Could you point me to which instructions you followed that were missing or provided incorrect information?

**Comment by arminfro** [comment]
Thank you for the fast response ;).
I'm using nixos with the netbird module provided by nixpkgs, I'm using the nix option [`services.netbird.server.management.oidcConfigEndpoint`](https://github.com/NixOS/nixpkgs/blob/8e44bd9c6668e9f69593acfae351b24ee25baff7/nixos/modules/services/networking/netbird/management.nix#L84). This value gets successfully written into `/var/lib/netbird-mgmt/management.json` but the web UI does not seem to use it.

**Comment by HEKPYTO** [comment]
Same issue here. `localhost/.well-known/openid-configuration:1  Failed to load resource: net::ERR_CONNECTION_REFUSED`,
on Netbird v0.52.0 with Authentik via Docker

In management container logs: 
```
INFO [context: SYSTEM] management/cmd/management.go:528: loaded OIDC configuration from the provided IDP configuration endpoint: https://authentik.<domain_name>/application/o/netbird/.well-known/openid-configuration
```

successfully loaded, but I am not sure that `localhost` trying to access offline scope ?

**Comment by dani3lsf** [comment]
Facing the same issue: GET http://localhost/.well-known/openid-configuration 404 Not Found
on Netbird 0.54.2 and dashboard v2.16.0 with Zitadel and k8s.

In management pod logs, I get:
```
2025-08-19T07:33:26Z INFO [context: SYSTEM] management/cmd/management.go:523: loading OIDC configuration from the provided IDP configuration endpoint https://<zitadel-domain>/.well-known/openid-configuration
```

Any fixes already?

**Comment by jschlitt-kupona** [comment]
Hi, I am facing exactly the same issue using Keycloak. Are there any updates?

Thanks

**Comment by nazarewk** [comment]
@dani3lsf @jschlitt-kupona can you try setting up `NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT` envvar? you should be able to provide an explicit address of the OIDC endpoint with it as per https://github.com/netbirdio/netbird/issues/2442#issuecomment-3106892099

**Comment by jschlitt-kupona** [comment]
Thanks alot for your fast reply.

This is not working for me, still getting the same error.

Here is my configuration with keycloak and traefik:

docker-compose.yaml
```yaml

x-default: &default
  restart: 'unless-stopped'
  logging:
    driver: 'json-file'
    options:
      max-size: '500m'
      max-file: '2'

services:
  # UI dashboard
  dashboard:
    <<: *default
    image: netbirdio/dashboard:latest
    container_name: netbird-dashboard
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://netbird.my-domain.de:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://netbird.my-domain.de:443
      # OIDC
      - AUTH_AUDIENCE=netbird-client
      - AUTH_CLIENT_ID=netbird-client
      - AUTH_CLIENT_SECRET=
      - AUTH_AUTHORITY=https://auth.my-domain.de/realms/my-realm
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
      - NETBIRD_TOKEN_SOURCE=accessToken
      - NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT=https://auth.my-domain.de/realms/my-realm/.well-known/openid-configuration
      # SSL
      - NGINX_SSL_PORT=443
      # Letsencrypt
      - LETSENCRYPT_DOMAIN=
      - LETSENCRYPT_EMAIL=
    # volumes:
    #   - netbird-letsencrypt:/etc/letsencrypt/
    networks:
      - proxy
      # - netbird
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-dashboard.rule=Host(`netbird.my-domain.de`)
    - traefik.http.services.netbird-dashboard.loadbalancer.server.port=80
    - traefik.http.routers.netbird-dashboard.tls=true
    - traefik.http.routers.netbird-dashboard.tls.certresolver=letsencrypt-production

  # Signal
  signal:
    <<: *default
    image: netbirdio/signal:latest
    container_name: netbird-signal
    volumes:
      - ./data/netbird-signal:/var/lib/netbird
    networks:
      - proxy
      - netbird
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-signal.rule=Host(`netbird.my-domain.de`) && PathPrefix(`/signalexchange.SignalExchange/`)
    - traefik.http.services.netbird-signal.loadbalancer.server.port=10000
    - traefik.http.services.netbird-signal.loadbalancer.server.scheme=h2c
    - traefik.http.routers.netbird-signal.tls=true
    - traefik.http.routers.netbird-signal.tls.certresolver=letsencrypt-production

  netbird-postgres:
    <<: *default
    image: postgres:latest
    container_name: netbird-postgres
    environment:
      POSTGRES_USER: netbird
      POSTGRES_PASSWORD: pg-password
      POSTGRES_DB: netbird
    volumes:
      - ./data/netbird-postgres:/var/lib/postgresql/data
    networks:
      - netbird

  # Relay
  relay:
    <<: *default
    image: netbirdio/relay:latest
    container_name: netbird-relay
    environment:
    - NB_LOG_LEVEL=info
    - NB_LISTEN_ADDRESS=:33080
    - NB_EXPOSED_ADDRESS=rels://netbird.my-domain.de:33080/relay
    # todo: change to a secure secret
    - NB_AUTH_SECRET=secret
    networks:
      - proxy
      - netbird
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-relay.rule=Host(`netbird.my-domain.de`) && PathPrefix(`/relay`)
    - traefik.http.services.netbird-relay.loadbalancer.server.port=33080
    - traefik.http.services.netbird-relay.loadbalancer.server.scheme=h2c
    - traefik.http.routers.netbird-relay.tls=true
    - traefik.http.routers.netbird-relay.tls.certresolver=letsencrypt-production

  # Management
  management:
    <<: *default
    image: netbirdio/management:latest
    container_name: netbird-management
    depends_on:
      - dashboard
    volumes:
      - ./data/netbird-mgmt:/var/lib/netbird
      # - netbird-letsencrypt:/etc/letsencrypt:ro
      - ./management.json:/etc/netbird/management.json
    command: [
      "--port", "33073",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.my-domain.de",
      "--dns-domain=netbird.selfhosted"
      ]
    networks:
      - proxy
      - netbird
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-api.rule=Host(`netbird.my-domain.de`) && PathPrefix(`/api`)
    - traefik.http.routers.netbird-api.service=netbird-api
    - traefik.http.services.netbird-api.loadbalancer.server.port=33073

    - traefik.http.routers.netbird-management.rule=Host(`netbird.my-domain.de`) && PathPrefix(`/management.ManagementService/`)
    - traefik.http.routers.netbird-management.service=netbird-management
    - traefik.http.services.netbird-management.loadbalancer.server.port=33073
    - traefik.http.services.netbird-management.loadbalancer.server.scheme=h2c
    - traefik.router.netbird-management.tls=true
    - traefik.router.netbird-management.tls.certresolver=letsencrypt-production
    environment:
      - NETBIRD_STORE_ENGINE_POSTGRES_DSN=postgres://netbird:pg-password@netbird-postgres:5432/netbird?sslmode=disable
      
  # Coturn
  coturn:
    <<: *default
    image: coturn/coturn:latest
    container_name: netbird-coturn
    domainname: netbird.my-domain.de
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
    network_mode: host
    command:
      - -c /etc/turnserver.conf
    # neetworks:
    #   - netbird

# volumes:
  # netbird-mgmt:
  # netbird-signal:
  # netbird-letsencrypt:

networks:
  proxy:
    external: true
    name: proxy
  netbird:
    external: false
    name: netbird
```

management.json
```json
{
    "Stuns": [
        {
            "Proto": "udp",
            "URI": "stun:netbird.my-domain.de:3478",
            "Username": "",
            "Password": ""
        }
    ],
    "TURNConfig": {
        "TimeBasedCredentials": false,
        "CredentialsTTL": "12h0m0s",
        "Secret": "secret",
        "Turns": [
            {
                "Proto": "udp",
                "URI": "turn:netbird.my-domain.de:3478",
                "Username": "self",
                "Password": "my-turn-password"
            }
        ]
    },
    "Relay": {
        "Addresses": [
            "rels://netbird.my-domain.de:33080/relay"
        ],
        "CredentialsTTL": "24h0m0s",
        "Secret": "my-relay-secret"
    },
    "Signal": {
        "Proto": "https",
        "URI": "netbird.my-domain.de:443",
        "Username": "",
        "Password": ""
    },
    "Datadir": "/var/lib/netbird/",
    "DataStoreEncryptionKey": "my-datastore-encryption-key",
    "HttpConfig": {
        "LetsEncryptDomain": "",
        "CertFile": "",
        "CertKey": "",
        "AuthAudience": "netbird-client",
        "AuthIssuer": "https://auth.my-domain.de/realms/my-realm",
        "AuthUserIDClaim": "",
        "AuthKeysLocation": "https://auth.my-domain.de/realms/my-realm/protocol/openid-connect/certs",
        "OIDCConfigEndpoint": "https://auth.my-domain.de/realms/my-realm/.well-known/openid-configuration",
        "IdpSignKeyRefreshEnabled": false,
        "ExtraAuthAudience": ""
    },
    "IdpManagerConfig": {
        "ManagerType": "keycloak",
        "ClientConfig": {
            "Issuer": "https://auth.my-domain.de/realms/my-realm",
            "TokenEndpoint": "https://auth.my-domain.de/realms/my-realm/protocol/openid-connect/token",
            "ClientID": "netbird-backend",
            "ClientSecret": "my-client-secret",
            "GrantType": "client_credentials"
        },
        "ExtraConfig": {
            "AdminEndpoint": "https://auth.my-domain.de/admin/realms/my-realm"
        },
        "Auth0ClientCredentials": null,
        "AzureClientCredentials": null,
        "KeycloakClientCredentials": null,
        "ZitadelClientCredentials": null
    },
    "DeviceAuthorizationFlow": {
        "Provider": "none",
        "ProviderConfig": {
            "ClientID": "",
            "ClientSecret": "",
            "Domain": "",
            "Audience": "netbird-client",
            "TokenEndpoint": "https://auth.my-domain.de/realms/my-realm/protocol/openid-connect/token",
            "DeviceAuthEndpoint": "https://auth.my-domain.de/realms/my-realm/protocol/openid-connect/auth/device",
            "AuthorizationEndpoint": "",
            "Scope": "openid",
            "UseIDToken": false,
            "RedirectURLs": null,
            "DisablePromptLogin": false,
            "LoginFlag": 0
        }
    },
    "PKCEAuthorizationFlow": {
        "ProviderConfig": {
            "ClientID": "netbird-client",
            "ClientSecret": "",
            "Domain": "",
            "Audience": "netbird-client",
            "TokenEndpoint": "https://auth.my-domain.de/realms/my-realm/protocol/openid-connect/token",
            "DeviceAuthEndpoint": "",
            "AuthorizationEndpoint": "https://auth.my-domain.de/realms/my-realm/protocol/openid-connect/auth",
            "Scope": "",
            "UseIDToken": false,
            "DisablePromptLogin": false,
            "LoginFlag": 0
        }
    },
    "StoreConfig": {
        "Engine": "postgres"
    },
    "ReverseProxy": {
        "TrustedHTTPProxies": [],
        "TrustedHTTPProxiesCount": 0,
        "TrustedPeers": [
            "0.0.0.0/0"
        ]
    },
    "DisableDefaultPolicy": false
}
```

This is the error in the browser console:

<img width="2490" height="771" alt="Image" src="https://github.com/user-attachments/assets/897613e1-4afd-43c5-8144-9160488ddf86" />

Here are the dashboards container logs:
```
+ LETSENCRYPT_DOMAIN=none

+ LETSENCRYPT_EMAIL=example@local

+ NGINX_SSL_PORT=443

+ '[' none-x == none-x ']'

+ exit 0

AUTH_SUPPORTED_SCOPES environment variable must be set

+ LETSENCRYPT_DOMAIN=none

+ LETSENCRYPT_EMAIL=example@local

+ NGINX_SSL_PORT=443

+ '[' none-x == none-x ']'

+ exit 0
```

I hope somebody can help me out.

Best regards

Jonathan
