### ISSUE TITLE
Destination Host Unreachable, ping: sendmsg: Required key not available

### ISSUE THREAD

**Issue by FarisZR** [netbirdio/netbird#254]
Hello, I have been using wiretrustee to expose a local server to a remote VPS.

However, every once in a while it stops working, and this happens:
## Logs
```
# ping 100.64.0.2
PING 100.64.0.2 (100.64.0.2) 56(84) bytes of data.
From 100.64.0.1 icmp_seq=1 Destination Host Unreachable
ping: sendmsg: Required key not available
From 100.64.0.1 icmp_seq=2 Destination Host Unreachable
ping: sendmsg: Required key not available
From 100.64.0.1 icmp_seq=3 Destination Host Unreachable
```

Removing both peers and re-adding them sometimes fixes it, or peers still can't ping each other.

## setup details

one peer is running wiretrustee inside docker, and the other is running a standard Debian installation inside an LXC, with [appropriate options](https://pve.proxmox.com/wiki/OpenVPN_in_LXC)

**Comment by mlsmaycon** [comment]
Hello @fariszr, can you share some details of your setup?


* Are you using the Managed version of Wiretrustee?
* Which version of Wiretrustee are the peers using? you can find that with `wiretrustee version` command
* Are the peers running on different nodes?
* Did you give privileged permissions to the Docker and LXC peers? for docker, we need to run with the flag `--cap-add=NET_ADMIN`

**Comment by fariszr** [comment]
> Hello @fariszr, can you share some details of your setup?
> 
> * Are you using the Managed version of Wiretrustee?
> * Which version of Wiretrustee are the peers using? you can find that with `wiretrustee version` command
> * Are the peers running on different nodes?
> * Did you give privileged permissions to the Docker and LXC peers? for docker, we need to run with the flag `--cap-add=NET_ADMIN`

1- yes
2 – Debian, 0.4.0. Docker, the latest image available from Docker hub using the latest tag.
3 – Yes, Totally different servers and hosting providers.
4 – LXC is Unprivileged, which worked, and I don't think it's the problem. 
I added the `net_admin` cap, It stopped showing `Required key not available` but ping still doesn't work.

## Wiretrustee logs
```
wiretrustee-wiretrustee-1  | time="2022-03-09T19:xx:xxZ" level=info msg="connected to peer p+xxxxxxxxxxxx= [laddr <-> raddr] [172.21.0.1:40908 <-> xx.xxx.xxx.192:55404]"
```

## Compose file
```
version: '3.3'
services:
    wiretrustee:
        network_mode: host
        privileged: true
        restart: always
        userns_mode: host
        environment:
            - WT_SETUP_KEY=XXXXXXXXX
        volumes:
            - ./wiretrustee-client:/etc/wiretrustee
        image: wiretrustee/wiretrustee:latest
        cap_add:
            - NET_ADMIN

```
