### ISSUE TITLE
Add DSN Configuration to management.json to unify postgre config.

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [netbirdio/netbird#2706]
I’d like to suggest a new feature for Netbird. It would be useful to add a key for handling the DSN directly in the `management.json` file. Currently, the engine is specified in `management.json`, while the DSN is set via an environment variable.

It would be great to consolidate this by allowing the DSN to be defined within `management.json`, like so:

```json
"StoreConfig": {
  "Engine": "postgres",
  "DSN": "xxxx"
}
```

This would simplify configuration management.

Thanks for considering this!

**Comment by PizzaLovingNerd** [comment]
Closing this as this issue is stale and modern versions of NetBird use a combined config.yaml which supports configurations like
```yaml
 server:
    store:
      engine: "postgres"
      dsn: "host=<PG_HOST> user=<PG_USER> password=<PG_PASSWORD> dbname=<PG_DB_NAME> port=<PG_PORT>"
```
Cheers!
