### ISSUE TITLE
Include a Docker Compose file suitable for QNAP QTS

### ISSUE THREAD

**Issue by trbutler** [netbirdio/netbird#2788]
**Is your feature request related to a problem? Please describe.**
QNAP NASes have RAM disk root drive that clears after every reboot, so the Synology installation instructions don't work for QNAP. This seems akin to the issue that motivates the [HomeAssistant add-on](https://github.com/netbirdio/addon-netbird). Like that add-on, a Docker container for the client helps resolve this issue, since the YAML file can be placed within Container Station.

**Describe the solution you'd like**
I've worked out a Docker compose file that makes Netbird work within QNAP, although I haven't figured out how to make Network routes work yet. This isn't identical to the HA docker compose file since I'd started working on this before I found it and, more importantly, that one seems to have some HA-specific requirements. 

Errata I've been unable to solve so far:

* While the NAS's IP address gets Netbird's DNS sitting on port 53, I haven't figure out how to gracefully integrate name resolution into QNAP's system yet.

* The Netbird docker container doesn't seem to add the network routes  to the system (either internal to the container or outside of it, since I'm using host networking), though they work if I add them manually, e.g. `ip route add 192.168.4.0/22 dev wt0`, etc.

````
services:
  netbird:
    image: netbirdio/netbird
    container_name: netbird
    hostname: netbird
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_RAW
      - BPF
    environment:
      - NB_SETUP_KEY=DD5B910D-2C1A-4543-9404-45FBAE628BE0
      - NB_MANAGEMENT_URL=https://sugarmaple.serverforest.com
      - NB_HOSTNAME=madison
      - NB_ENABLE_ROSENPASS=1
      - NB_ROSENPASS_PERMISSIVE=1
    volumes:
      - netbird-client:/etc/netbird
    restart: unless-stopped

volumes:
  netbird-client:
````

**Describe alternatives you've considered**
I've participated in another issue about [a native package for QNAP](https://github.com/netbirdio/netbird/issues/2748#issuecomment-2418989635), although this is a lot less complicated, not requiring either keeping up with Netbird releases _or_ an Entware package being added to the Netbird build system.
