### ISSUE TITLE
Coturn doesn't read the turnserver.conf when selfhosting netbird

### ISSUE THREAD

**Issue by oskardotglobal** [netbirdio/netbird#630]
**Describe the problem**
The turnserver doesn't work properly when selfhosting. This is because the `turnserver.conf` is never read by coturn. The log shows:
```
netbird-coturn-1  | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
```

**Solution**
Point coturn to the turnserver.conf by adding the following lines to the `docker-compose.yml.tmpl`:

```yml
services:
  ...
  coturn:
    ...
    command:
      - -c /etc/turnserver.conf
```

According to the Documentation on https://hub.docker.com/r/coturn/coturn the default config location is `/etc/coturn/turnserver.conf`, not `/etc/turnserver.conf`:
![](https://i.postimg.cc/9MXbkpQX/Unbenannt.png)

I opened a PR #633
