### ISSUE TITLE
AllowedIP without routing

### ISSUE THREAD

**Issue by stevefan1999-personal** [netbirdio/netbird#695]
**Is your feature request related to a problem? Please describe.**

I need to use Calico with my k0s cluster and I need to have allowed IP without auto IP route in netbird, because Calico already handled routing by using BIRD and will intelligently select wt0 as the gateway. But because my pod and service CIDR is not in the allowed IP list, I got required keys error which indeed is because the IP is not allowef

**Describe the solution you'd like**
Allow the option to disable route but keep allowed IPs

**Describe alternatives you've considered**
Use VXLAN on top of wt0, no dice
Use another wireguard on top of wt0 (Calico supports wireguard too), cannot create IP socket

**Additional context**

**Comment by KlavsKlavsen** [comment]
Yeah.. we finally got time to start trying out netbird - but are stuck on this :(

**Comment by ashish1099** [comment]
Adding a bgpconfiguration which made this work.

```yaml
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Error
  nodeToNodeMeshEnabled: false
  asNumber: 64512
  ```
  
  I got the idea from here https://github.com/projectcalico/calico/issues/3760#issuecomment-808418033
