### ISSUE TITLE
Dex IdP Integration

### ISSUE THREAD

**Issue by boynoiz** [netbirdio/netbird#898]
Is there any guide for setup Netbird self-host with Dex IdP?
or plan for supporting Dex IdP?

**Comment by mlsmaycon** [comment]
Hello @boynoiz we are looking into adding DEX as one of our supported integrations. Below you find a sample configuration for it.

```yaml
issuer: https://auth.example.com/

storage:
  type: sqlite3
  config:
    file: examples/dex.db

# HTTP service configuration
web:
  http: 0.0.0.0:9000
  allowedOrigins: ['*']

frontend:
  issuer: dex
  logoURL: https://github.com/netbirdio/netbird/blob/main/docs/media/logo-full.png
  dir: /opt/dex/web

# OAuth2 configuration
oauth2:
  responseTypes: ["code", "token", "id_token"] # also allowed are "token" and "id_token"
  skipApprovalScreen: false
  alwaysShowLoginScreen: true

staticClients:
  - id: netbird-dex
    public: true
    redirectURIs:
      - 'https://netbird.example.com/#callback'
      - '/device/callback'
    name: 'Netbird VPN'

connectors:
- type: mockCallback
  id: mock
  name: Example

enablePasswordDB: true
# A static list of passwords to login the end user. By identifying here, dex
# won't look in its underlying storage for passwords.
#
# If this option isn't chosen users may be added through the gRPC API.
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
  hash: "$2a$10$23jbrk1bkjl1nk3ln2k3rnkjnrkj4nrkj3n4kj3n4jkrn3kj4"
  username: "admin"
  userID: "92929292-db88-3333-22222-111111"
```  

Maybe @Thunderbottom would have a bit more of insights into the dashboard and management settings.
